//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account has been added!.
        /// </summary>
        internal static string AccountAddedSuccess {
            get {
                return ResourceManager.GetString("AccountAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account.
        /// </summary>
        internal static string AccountLabel {
            get {
                return ResourceManager.GetString("AccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account name.
        /// </summary>
        internal static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose an account..
        /// </summary>
        internal static string AccountRequiredMsg {
            get {
                return ResourceManager.GetString("AccountRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accounts.
        /// </summary>
        internal static string AccountsPageTitle {
            get {
                return ResourceManager.GetString("AccountsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter a valid amount (e.g., 100.00)..
        /// </summary>
        internal static string AccountValidationInvalidAmount {
            get {
                return ResourceManager.GetString("AccountValidationInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter the account name and select a currency..
        /// </summary>
        internal static string AccountValidationMissingData {
            get {
                return ResourceManager.GetString("AccountValidationMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Account.
        /// </summary>
        internal static string AddAccountBtn {
            get {
                return ResourceManager.GetString("AddAccountBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Category.
        /// </summary>
        internal static string AddCategoryBtn {
            get {
                return ResourceManager.GetString("AddCategoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add project.
        /// </summary>
        internal static string AddProjectBtn {
            get {
                return ResourceManager.GetString("AddProjectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Exchange Rate.
        /// </summary>
        internal static string AddRateBtn {
            get {
                return ResourceManager.GetString("AddRateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Transaction.
        /// </summary>
        internal static string AddTransactionTitle {
            get {
                return ResourceManager.GetString("AddTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All categories.
        /// </summary>
        internal static string AllCategoriesLabel {
            get {
                return ResourceManager.GetString("AllCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All projects.
        /// </summary>
        internal static string AllProjectsLabel {
            get {
                return ResourceManager.GetString("AllProjectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transactions list.
        /// </summary>
        internal static string AllTransactionsTitle {
            get {
                return ResourceManager.GetString("AllTransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter a valid amount greater than zero..
        /// </summary>
        internal static string AmountInvalidMsg {
            get {
                return ResourceManager.GetString("AmountInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount.
        /// </summary>
        internal static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Initial Balance.
        /// </summary>
        internal static string BalanceLabel {
            get {
                return ResourceManager.GetString("BalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Categories.
        /// </summary>
        internal static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color.
        /// </summary>
        internal static string CategoryColorLabel {
            get {
                return ResourceManager.GetString("CategoryColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category.
        /// </summary>
        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category name.
        /// </summary>
        internal static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu None.
        /// </summary>
        internal static string CategoryNone {
            get {
                return ResourceManager.GetString("CategoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parent category (optional).
        /// </summary>
        internal static string CategoryParentLabel {
            get {
                return ResourceManager.GetString("CategoryParentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UAE Dirham.
        /// </summary>
        internal static string Currency_AED {
            get {
                return ResourceManager.GetString("Currency_AED", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Australian Dollar.
        /// </summary>
        internal static string Currency_AUD {
            get {
                return ResourceManager.GetString("Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bulgarian Lev.
        /// </summary>
        internal static string Currency_BGN {
            get {
                return ResourceManager.GetString("Currency_BGN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Canadian Dollar.
        /// </summary>
        internal static string Currency_CAD {
            get {
                return ResourceManager.GetString("Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Swiss Franc.
        /// </summary>
        internal static string Currency_CHF {
            get {
                return ResourceManager.GetString("Currency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chinese Yuan.
        /// </summary>
        internal static string Currency_CNY {
            get {
                return ResourceManager.GetString("Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czech Koruna.
        /// </summary>
        internal static string Currency_CZK {
            get {
                return ResourceManager.GetString("Currency_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Danish Krone.
        /// </summary>
        internal static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Euro.
        /// </summary>
        internal static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu British Pound.
        /// </summary>
        internal static string Currency_GBP {
            get {
                return ResourceManager.GetString("Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hungarian Forint.
        /// </summary>
        internal static string Currency_HUF {
            get {
                return ResourceManager.GetString("Currency_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Israeli New Shekel.
        /// </summary>
        internal static string Currency_ILS {
            get {
                return ResourceManager.GetString("Currency_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Japanese Yen.
        /// </summary>
        internal static string Currency_JPY {
            get {
                return ResourceManager.GetString("Currency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Norwegian Krone.
        /// </summary>
        internal static string Currency_NOK {
            get {
                return ResourceManager.GetString("Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polish Zloty.
        /// </summary>
        internal static string Currency_PLN {
            get {
                return ResourceManager.GetString("Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Romanian Leu.
        /// </summary>
        internal static string Currency_RON {
            get {
                return ResourceManager.GetString("Currency_RON", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Swedish Krona.
        /// </summary>
        internal static string Currency_SEK {
            get {
                return ResourceManager.GetString("Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turkish Lira.
        /// </summary>
        internal static string Currency_TRY {
            get {
                return ResourceManager.GetString("Currency_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ukrainian Hryvnia.
        /// </summary>
        internal static string Currency_UAH {
            get {
                return ResourceManager.GetString("Currency_UAH", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu US Dollar.
        /// </summary>
        internal static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currency.
        /// </summary>
        internal static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expenses this month:.
        /// </summary>
        internal static string CurrentMonthExpensesLabel {
            get {
                return ResourceManager.GetString("CurrentMonthExpensesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Danger zone.
        /// </summary>
        internal static string DangerZone {
            get {
                return ResourceManager.GetString("DangerZone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data Management.
        /// </summary>
        internal static string DataSettingsLabel {
            get {
                return ResourceManager.GetString("DataSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default currency.
        /// </summary>
        internal static string DefaultCurrencyLabel {
            get {
                return ResourceManager.GetString("DefaultCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning: Subcategories will also be deleted!.
        /// </summary>
        internal static string DeleteCatCascadeInlineWarning {
            get {
                return ResourceManager.GetString("DeleteCatCascadeInlineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This category has subcategories. Deleting it will also archive all of them. Are you sure you want to continue?.
        /// </summary>
        internal static string DeleteCatCascadeWarningMsg {
            get {
                return ResourceManager.GetString("DeleteCatCascadeWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete?.
        /// </summary>
        internal static string DeleteConfirmationText {
            get {
                return ResourceManager.GetString("DeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning: Subprojects will also be deleted!.
        /// </summary>
        internal static string DeleteProjCascadeInlineWarning {
            get {
                return ResourceManager.GetString("DeleteProjCascadeInlineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This project has subprojects. Deleting it will also archive all of them. Are you sure you want to continue?.
        /// </summary>
        internal static string DeleteProjCascadeWarningMsg {
            get {
                return ResourceManager.GetString("DeleteProjCascadeWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To Account.
        /// </summary>
        internal static string DestinationAccountLabel {
            get {
                return ResourceManager.GetString("DestinationAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DESTROY DATA.
        /// </summary>
        internal static string DestroyDataBtn {
            get {
                return ResourceManager.GetString("DestroyDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        internal static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense.
        /// </summary>
        internal static string Enum_Expense {
            get {
                return ResourceManager.GetString("Enum_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string Enum_Income {
            get {
                return ResourceManager.GetString("Enum_Income", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transfer.
        /// </summary>
        internal static string Enum_Transfer {
            get {
                return ResourceManager.GetString("Enum_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occured..
        /// </summary>
        internal static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error loading dashboard:.
        /// </summary>
        internal static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password cannot be empty!.
        /// </summary>
        internal static string ErrorPasswordEmpty {
            get {
                return ResourceManager.GetString("ErrorPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Passwords do not match!.
        /// </summary>
        internal static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter the correct currency exchange rate..
        /// </summary>
        internal static string ExchangeRateInvalidMsg {
            get {
                return ResourceManager.GetString("ExchangeRateInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exchange Rate.
        /// </summary>
        internal static string ExchangeRateLabel {
            get {
                return ResourceManager.GetString("ExchangeRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Favorite Currencies.
        /// </summary>
        internal static string FavoriteCurrenciesTitle {
            get {
                return ResourceManager.GetString("FavoriteCurrenciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount.
        /// </summary>
        internal static string HeaderAmount {
            get {
                return ResourceManager.GetString("HeaderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category.
        /// </summary>
        internal static string HeaderCategory {
            get {
                return ResourceManager.GetString("HeaderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        internal static string HeaderDate {
            get {
                return ResourceManager.GetString("HeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        internal static string HeaderDescription {
            get {
                return ResourceManager.GetString("HeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project.
        /// </summary>
        internal static string HeaderProject {
            get {
                return ResourceManager.GetString("HeaderProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Language:.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manage Categories.
        /// </summary>
        internal static string ManageCategoriesBtn {
            get {
                return ResourceManager.GetString("ManageCategoriesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exchange Rates.
        /// </summary>
        internal static string ManageExchangeRatesTitle {
            get {
                return ResourceManager.GetString("ManageExchangeRatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manage Favorite Currencies.
        /// </summary>
        internal static string ManageFavoriteCurrenciesBtn {
            get {
                return ResourceManager.GetString("ManageFavoriteCurrenciesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manage Projects.
        /// </summary>
        internal static string ManageProjectsBtn {
            get {
                return ResourceManager.GetString("ManageProjectsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Max Amount.
        /// </summary>
        internal static string MaxAmountPlaceholder {
            get {
                return ResourceManager.GetString("MaxAmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Min Amount.
        /// </summary>
        internal static string MinAmountPlaceholder {
            get {
                return ResourceManager.GetString("MinAmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The application used an emergency 1:1 conversion rate for the following currencies because their rates are missing in the database:.
        /// </summary>
        internal static string MissingRatesMsgPart1 {
            get {
                return ResourceManager.GetString("MissingRatesMsgPart1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add the missing rates in the settings to calculate the total net worth correctly..
        /// </summary>
        internal static string MissingRatesMsgPart2 {
            get {
                return ResourceManager.GetString("MissingRatesMsgPart2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing exchange rates.
        /// </summary>
        internal static string MissingRatesTitle {
            get {
                return ResourceManager.GetString("MissingRatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total Net Worth.
        /// </summary>
        internal static string NetWorthLabel {
            get {
                return ResourceManager.GetString("NetWorthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No transactions ....
        /// </summary>
        internal static string NoTransactionsLabel {
            get {
                return ResourceManager.GetString("NoTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OK.
        /// </summary>
        internal static string OkBtn {
            get {
                return ResourceManager.GetString("OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu  Others.
        /// </summary>
        internal static string OtherCategories {
            get {
                return ResourceManager.GetString("OtherCategories", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project (Optional).
        /// </summary>
        internal static string ProjectLabel {
            get {
                return ResourceManager.GetString("ProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project Name.
        /// </summary>
        internal static string ProjectNameLabel {
            get {
                return ResourceManager.GetString("ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Projects.
        /// </summary>
        internal static string ProjectsTitle {
            get {
                return ResourceManager.GetString("ProjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter project name..
        /// </summary>
        internal static string ProjectValidationMissingData {
            get {
                return ResourceManager.GetString("ProjectValidationMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rate (e.g. 4,35).
        /// </summary>
        internal static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recent Transactions.
        /// </summary>
        internal static string RecentTransactionsLabel {
            get {
                return ResourceManager.GetString("RecentTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save changes.
        /// </summary>
        internal static string SaveChangesBtn {
            get {
                return ResourceManager.GetString("SaveChangesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Transaction.
        /// </summary>
        internal static string SaveTransactionBtn {
            get {
                return ResourceManager.GetString("SaveTransactionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search (description, category)....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Confirm password....
        /// </summary>
        internal static string SetupConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SetupConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Secure your database with a master password. This password will be the encryption key for all your financial data..
        /// </summary>
        internal static string SetupDescription {
            get {
                return ResourceManager.GetString("SetupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter new password....
        /// </summary>
        internal static string SetupPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SetupPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 🛡️ Security.
        /// </summary>
        internal static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome to ExpenseTracker!.
        /// </summary>
        internal static string SetupWelcome {
            get {
                return ResourceManager.GetString("SetupWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu From Currency.
        /// </summary>
        internal static string SourceCurrencyLabel {
            get {
                return ResourceManager.GetString("SourceCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To Currency.
        /// </summary>
        internal static string TargetCurrencyLabel {
            get {
                return ResourceManager.GetString("TargetCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu High Contrast.
        /// </summary>
        internal static string ThemeHighContrast {
            get {
                return ResourceManager.GetString("ThemeHighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Theme:.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your Accounts.
        /// </summary>
        internal static string TotalBalanceLabel {
            get {
                return ResourceManager.GetString("TotalBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account transactions.
        /// </summary>
        internal static string TransactionsPageTitle {
            get {
                return ResourceManager.GetString("TransactionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select the correct destination account (different from the source account)..
        /// </summary>
        internal static string TransferAccountInvalidMsg {
            get {
                return ResourceManager.GetString("TransferAccountInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transaction Type.
        /// </summary>
        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Got it.
        /// </summary>
        internal static string UnderstoodBtn {
            get {
                return ResourceManager.GetString("UnderstoodBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wipe application data.
        /// </summary>
        internal static string WipeDataBtn {
            get {
                return ResourceManager.GetString("WipeDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All accounts, transactions, categories, and projects will be permanently destroyed. Continue?.
        /// </summary>
        internal static string WipeDataFinalWarningMessage {
            get {
                return ResourceManager.GetString("WipeDataFinalWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu FINAL WARNING.
        /// </summary>
        internal static string WipeDataFinalWarningTitle {
            get {
                return ResourceManager.GetString("WipeDataFinalWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The application has been restored to factory settings..
        /// </summary>
        internal static string WipeDataSuccessMessage {
            get {
                return ResourceManager.GetString("WipeDataSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete all data? This operation is irreversible..
        /// </summary>
        internal static string WipeDataWarningMessage {
            get {
                return ResourceManager.GetString("WipeDataWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        internal static string YesBtn {
            get {
                return ResourceManager.GetString("YesBtn", resourceCulture);
            }
        }
    }
}
