//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account.
        /// </summary>
        internal static string AccountLabel {
            get {
                return ResourceManager.GetString("AccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account name.
        /// </summary>
        internal static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accounts.
        /// </summary>
        internal static string AccountsPageTitle {
            get {
                return ResourceManager.GetString("AccountsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Account.
        /// </summary>
        internal static string AddAccountBtn {
            get {
                return ResourceManager.GetString("AddAccountBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Category.
        /// </summary>
        internal static string AddCategoryBtn {
            get {
                return ResourceManager.GetString("AddCategoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add project.
        /// </summary>
        internal static string AddProjectBtn {
            get {
                return ResourceManager.GetString("AddProjectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Exchange Rate.
        /// </summary>
        internal static string AddRateBtn {
            get {
                return ResourceManager.GetString("AddRateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Transaction.
        /// </summary>
        internal static string AddTransactionTitle {
            get {
                return ResourceManager.GetString("AddTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount.
        /// </summary>
        internal static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Initial Balance.
        /// </summary>
        internal static string BalanceLabel {
            get {
                return ResourceManager.GetString("BalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Categories.
        /// </summary>
        internal static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category.
        /// </summary>
        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category name.
        /// </summary>
        internal static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UAE Dirham.
        /// </summary>
        internal static string Currency_AED {
            get {
                return ResourceManager.GetString("Currency_AED", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Australian Dollar.
        /// </summary>
        internal static string Currency_AUD {
            get {
                return ResourceManager.GetString("Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bulgarian Lev.
        /// </summary>
        internal static string Currency_BGN {
            get {
                return ResourceManager.GetString("Currency_BGN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Canadian Dollar.
        /// </summary>
        internal static string Currency_CAD {
            get {
                return ResourceManager.GetString("Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Swiss Franc.
        /// </summary>
        internal static string Currency_CHF {
            get {
                return ResourceManager.GetString("Currency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chinese Yuan.
        /// </summary>
        internal static string Currency_CNY {
            get {
                return ResourceManager.GetString("Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czech Koruna.
        /// </summary>
        internal static string Currency_CZK {
            get {
                return ResourceManager.GetString("Currency_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Danish Krone.
        /// </summary>
        internal static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Euro.
        /// </summary>
        internal static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu British Pound.
        /// </summary>
        internal static string Currency_GBP {
            get {
                return ResourceManager.GetString("Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hungarian Forint.
        /// </summary>
        internal static string Currency_HUF {
            get {
                return ResourceManager.GetString("Currency_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Israeli New Shekel.
        /// </summary>
        internal static string Currency_ILS {
            get {
                return ResourceManager.GetString("Currency_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Japanese Yen.
        /// </summary>
        internal static string Currency_JPY {
            get {
                return ResourceManager.GetString("Currency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Norwegian Krone.
        /// </summary>
        internal static string Currency_NOK {
            get {
                return ResourceManager.GetString("Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polish Zloty.
        /// </summary>
        internal static string Currency_PLN {
            get {
                return ResourceManager.GetString("Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Romanian Leu.
        /// </summary>
        internal static string Currency_RON {
            get {
                return ResourceManager.GetString("Currency_RON", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Swedish Krona.
        /// </summary>
        internal static string Currency_SEK {
            get {
                return ResourceManager.GetString("Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turkish Lira.
        /// </summary>
        internal static string Currency_TRY {
            get {
                return ResourceManager.GetString("Currency_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ukrainian Hryvnia.
        /// </summary>
        internal static string Currency_UAH {
            get {
                return ResourceManager.GetString("Currency_UAH", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu US Dollar.
        /// </summary>
        internal static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currency.
        /// </summary>
        internal static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data Management.
        /// </summary>
        internal static string DataSettingsLabel {
            get {
                return ResourceManager.GetString("DataSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default currency.
        /// </summary>
        internal static string DefaultCurrencyLabel {
            get {
                return ResourceManager.GetString("DefaultCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Description.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To Account.
        /// </summary>
        internal static string DestinationAccountLabel {
            get {
                return ResourceManager.GetString("DestinationAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense.
        /// </summary>
        internal static string Enum_Expense {
            get {
                return ResourceManager.GetString("Enum_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string Enum_Income {
            get {
                return ResourceManager.GetString("Enum_Income", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transfer.
        /// </summary>
        internal static string Enum_Transfer {
            get {
                return ResourceManager.GetString("Enum_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exchange Rate.
        /// </summary>
        internal static string ExchangeRateLabel {
            get {
                return ResourceManager.GetString("ExchangeRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Favorite Currencies.
        /// </summary>
        internal static string FavoriteCurrenciesTitle {
            get {
                return ResourceManager.GetString("FavoriteCurrenciesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Language:.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manage Categories.
        /// </summary>
        internal static string ManageCategoriesBtn {
            get {
                return ResourceManager.GetString("ManageCategoriesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exchange Rates.
        /// </summary>
        internal static string ManageExchangeRatesTitle {
            get {
                return ResourceManager.GetString("ManageExchangeRatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manage Favorite Currencies.
        /// </summary>
        internal static string ManageFavoriteCurrenciesBtn {
            get {
                return ResourceManager.GetString("ManageFavoriteCurrenciesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manage Projects.
        /// </summary>
        internal static string ManageProjectsBtn {
            get {
                return ResourceManager.GetString("ManageProjectsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total Net Worth.
        /// </summary>
        internal static string NetWorthLabel {
            get {
                return ResourceManager.GetString("NetWorthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No transactions ....
        /// </summary>
        internal static string NoTransactionsLabel {
            get {
                return ResourceManager.GetString("NoTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project (Optional).
        /// </summary>
        internal static string ProjectLabel {
            get {
                return ResourceManager.GetString("ProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Project Name.
        /// </summary>
        internal static string ProjectNameLabel {
            get {
                return ResourceManager.GetString("ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Projects.
        /// </summary>
        internal static string ProjectsTitle {
            get {
                return ResourceManager.GetString("ProjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rate (e.g. 4,35).
        /// </summary>
        internal static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recent Transactions.
        /// </summary>
        internal static string RecentTransactionsLabel {
            get {
                return ResourceManager.GetString("RecentTransactionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Transaction.
        /// </summary>
        internal static string SaveTransactionBtn {
            get {
                return ResourceManager.GetString("SaveTransactionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu From Currency.
        /// </summary>
        internal static string SourceCurrencyLabel {
            get {
                return ResourceManager.GetString("SourceCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To Currency.
        /// </summary>
        internal static string TargetCurrencyLabel {
            get {
                return ResourceManager.GetString("TargetCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu High Contrast.
        /// </summary>
        internal static string ThemeHighContrast {
            get {
                return ResourceManager.GetString("ThemeHighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Theme:.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your Accounts.
        /// </summary>
        internal static string TotalBalanceLabel {
            get {
                return ResourceManager.GetString("TotalBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transaction Type.
        /// </summary>
        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
    }
}
